# Eventos básicos de nginx
events {}

http {
    # Grupo de servidores disponibles
    # Nginx repartirá las peticiones
    upstream servidores {
        # Primer servidor Flask
        server formulario:8100;
        # Segundo servidor Flask
        server formulario2:8100;
    }

    server {
        # Puerto donde escucha nginx
        listen 80;
        # Todas las peticiones pasan al grupo anterior
        location / {
            # Balanceador de carga
            proxy_pass http://servidores;

        }
    }
}